export const CONFIG = {
  DEFAULT_PORT: 3000,
  API_PREFIX: '/api',
  HEALTH_ENDPOINT: '/health',
  DATABASE_TIMEOUT: 5000,
  MAX_USERS_PER_PAGE: 50
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500
};